include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    deprecated_member_use: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
