// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiSlQMTCQo5bGng0xExkhPrKFSCqoPnJ0',
    appId: '1:1067718010231:web:cbc5e5427c2b8cc1512d72',
    messagingSenderId: '1067718010231',
    projectId: 'pokedex-app-c5e90',
    authDomain: 'pokedex-app-c5e90.firebaseapp.com',
    storageBucket: 'pokedex-app-c5e90.firebasestorage.app',
    measurementId: 'G-H99H59YKTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaXKu6XlPza36l9UzlN2DpYKpkPTByFLs',
    appId: '1:1067718010231:android:d19883d16e5f00f0512d72',
    messagingSenderId: '1067718010231',
    projectId: 'pokedex-app-c5e90',
    storageBucket: 'pokedex-app-c5e90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IfXePFD8mxd1jxkPu4V5U-n91GZw-5A',
    appId: '1:1067718010231:ios:7b56021f4d2d1625512d72',
    messagingSenderId: '1067718010231',
    projectId: 'pokedex-app-c5e90',
    storageBucket: 'pokedex-app-c5e90.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );
}
